version: '3'
services:
  ossasea-app:
    image: ossasea-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/osasea
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - ossasea-net

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osasea
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ossasea-net
    ports:
      - "3306:3306"

networks:
  ossasea-net:
    driver: bridge

volumes:
  db_data: