apiVersion: apps/v1
kind: Deployment
metadata:
  name: ossasea-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ossasea-app
  template:
    metadata:
      labels:
        app: ossasea-app
    spec:
      containers:
        - name: ossasea-app
          image: your-dockerhub-username/ossasea-app:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/osasea
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
        - name: mysql-db
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: osasea
---
apiVersion: v1
kind: Service
metadata:
  name: ossasea-service
spec:
  type: LoadBalancer
  selector:
    app: ossasea-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081