apiVersion: v1
kind: Service
metadata:
  name: rapidrelease-app-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: rapidrelease-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081